[project]
name = "kv-cache-optimization-multi-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thisischeese", email = "iamclwm@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
kv-cache-optimization-multi-agents = "kv_cache_optimization_multi_agents:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
